import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
const evidence=v.object({path:v.string(),startLine:v.number(),endLine:v.number(),excerpt:v.string(),explanation:v.string(),githubPermalink:v.optional(v.string())});
export default defineSchema({
 users:defineTable({email:v.optional(v.string()),telegramUserId:v.optional(v.string()),createdAt:v.number(),firstUseAt:v.optional(v.number())}).index('by_telegram',['telegramUserId']),
 runs:defineTable({publicId:v.string(),userId:v.optional(v.id('users')),telegramUserId:v.optional(v.string()),repository:v.string(),owner:v.string(),name:v.string(),goal:v.string(),mode:v.union(v.literal('audit_only'),v.literal('guarded_repair')),status:v.string(),currentStage:v.string(),promptVersion:v.string(),hermesSessionId:v.optional(v.string()),hermesRunId:v.optional(v.string()),createdAt:v.number(),startedAt:v.optional(v.number()),completedAt:v.optional(v.number()),elapsedMs:v.optional(v.number()),dashboardSlug:v.string(),prUrl:v.optional(v.string()),error:v.optional(v.string()),mappedFiles:v.number(),flowCount:v.number(),confirmedFindingCount:v.number(),rejectedFindingCount:v.number(),verifiedRepairCount:v.number(),revertedRepairCount:v.number(),dependencyRiskCount:v.number(),analysisMode:v.union(v.literal('initial_full'),v.literal('incremental')),inputSchemaSnapshotId:v.optional(v.string()),outputSchemaSnapshotId:v.optional(v.string()),changedFileCount:v.number(),impactedFlowCount:v.number(),brief:v.optional(v.any()),capabilityProfile:v.optional(v.any()),paused:v.boolean(),conservativeRepair:v.boolean()}).index('by_public_id',['publicId']).index('by_repository',['repository']).index('by_status',['status']).index('by_telegram',['telegramUserId']),
 agentSteps:defineTable({runId:v.id('runs'),stepId:v.string(),parentStepId:v.optional(v.string()),role:v.string(),dynamicallySpawned:v.boolean(),objective:v.string(),status:v.string(),startedAt:v.number(),finishedAt:v.optional(v.number()),latencyMs:v.optional(v.number()),inputSummary:v.string(),outputSummary:v.optional(v.string()),tools:v.array(v.string()),revisions:v.array(v.string()),error:v.optional(v.string()),tokenUse:v.optional(v.number()),costUsd:v.optional(v.number())}).index('by_run',['runId']).index('by_parent',['runId','parentStepId']).index('by_status',['status']),
 graphNodes:defineTable({runId:v.id('runs'),nodeId:v.string(),kind:v.string(),name:v.string(),path:v.optional(v.string()),startLine:v.optional(v.number()),endLine:v.optional(v.number()),summary:v.string(),confidence:v.number()}).index('by_run',['runId']),
 graphEdges:defineTable({runId:v.id('runs'),edgeId:v.string(),from:v.string(),to:v.string(),kind:v.string(),evidence:v.array(evidence),confidence:v.number()}).index('by_run',['runId']),
 flows:defineTable({runId:v.id('runs'),flowId:v.string(),name:v.string(),data:v.any()}).index('by_run',['runId']),
 schemaSnapshots:defineTable({repositoryKey:v.string(),snapshotId:v.string(),version:v.number(),parentSnapshotId:v.optional(v.string()),sourceCommitSha:v.optional(v.string()),data:v.any(),createdAt:v.number(),confidenceSummary:v.string()}).index('by_repository_version',['repositoryKey','version']).index('by_snapshot_id',['snapshotId']),
 schemaDeltas:defineTable({runId:v.id('runs'),deltaId:v.string(),data:v.any(),createdAt:v.number()}).index('by_run',['runId']),
 principles:defineTable({runId:v.id('runs'),principleId:v.string(),statement:v.string(),scope:v.any(),provenance:v.array(v.string()),evidence:v.array(evidence),confidence:v.number(),status:v.string(),approvedExceptions:v.array(v.string()),lastValidatedAt:v.optional(v.number())}).index('by_run',['runId']),
 preferences:defineTable({repositoryKey:v.string(),preferenceId:v.string(),category:v.string(),value:v.string(),source:v.string(),evidence:v.array(evidence),confidence:v.number(),active:v.boolean()}).index('by_repository',['repositoryKey']),
 editorDiagnostics:defineTable({runId:v.id('runs'),repositoryKey:v.string(),findingId:v.string(),path:v.string(),startLine:v.number(),endLine:v.number(),severity:v.string(),title:v.string(),flowLabel:v.string(),principleStatement:v.string(),impact:v.string(),repairStatus:v.string(),dashboardUrl:v.string(),githubPermalink:v.optional(v.string())}).index('by_run',['runId']).index('by_repository_path',['repositoryKey','path']),
 findings:defineTable({runId:v.id('runs'),findingId:v.string(),title:v.string(),category:v.string(),severity:v.string(),confidence:v.number(),status:v.string(),impact:v.string(),logicChain:v.array(v.string()),evidence:v.array(evidence),affectedNodeIds:v.array(v.string()),affectedFlowIds:v.array(v.string()),violatedInvariantIds:v.array(v.string()),businessImpact:v.string(),recommendation:v.string(),repairability:v.string(),rejectionReason:v.optional(v.string())}).index('by_run',['runId']).index('by_status',['status']),
 dependencies:defineTable({runId:v.id('runs'),packageName:v.string(),data:v.any()}).index('by_run',['runId']),
 repairs:defineTable({runId:v.id('runs'),repairId:v.string(),findingId:v.string(),status:v.string(),data:v.any()}).index('by_run',['runId']).index('by_status',['status']),
 validations:defineTable({runId:v.id('runs'),repairId:v.string(),check:v.string(),status:v.string(),durationMs:v.optional(v.number()),summary:v.string(),artifactUrl:v.optional(v.string())}).index('by_run',['runId']),
 repoMemories:defineTable({repositoryKey:v.string(),runId:v.id('runs'),snapshotId:v.string(),summary:v.string(),data:v.any(),createdAt:v.number()}).index('by_repository_created',['repositoryKey','createdAt']),
 roles:defineTable({name:v.string(),version:v.string(),enabled:v.boolean(),objective:v.string(),tools:v.array(v.string()),guardrails:v.array(v.string()),dynamic:v.boolean()}).index('by_name',['name']),
 evalCases:defineTable({caseId:v.string(),name:v.string(),version:v.string(),expected:v.any()}).index('by_case_id',['caseId']),
 evalRuns:defineTable({version:v.string(),startedAt:v.number(),completedAt:v.number(),passed:v.number(),failed:v.number(),data:v.any()}).index('by_version',['version']),
 managementActions:defineTable({runId:v.id('runs'),action:v.string(),actor:v.string(),createdAt:v.number(),details:v.optional(v.any())}).index('by_run',['runId'])
});
