import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
const evidence=v.object({path:v.string(),startLine:v.number(),endLine:v.number(),excerpt:v.string(),explanation:v.string(),githubPermalink:v.optional(v.string())});
export default defineSchema({
 users:defineTable({email:v.optional(v.string()),telegramUserId:v.optional(v.string()),createdAt:v.number(),firstUseAt:v.optional(v.number())}).index('by_telegram',['telegramUserId']),
 runs:defineTable({publicId:v.string(),userId:v.optional(v.id('users')),telegramUserId:v.optional(v.string()),telegramChatId:v.optional(v.string()),telegramThreadId:v.optional(v.string()),repository:v.string(),owner:v.string(),name:v.string(),goal:v.string(),requestedSourceCommitSha:v.optional(v.string()),defaultBranch:v.optional(v.string()),mode:v.literal('audit_only'),status:v.string(),currentStage:v.string(),promptVersion:v.string(),hermesSessionId:v.optional(v.string()),hermesRunId:v.optional(v.string()),hermesVerifierRunId:v.optional(v.string()),roleProofDigest:v.optional(v.string()),releaseTreeSha:v.optional(v.string()),releaseSourceDigest:v.optional(v.string()),runtimeIdentityDigest:v.optional(v.string()),runtimeProcessPid:v.optional(v.number()),runtimeBootNonce:v.optional(v.string()),sourceCommitSha:v.optional(v.string()),snapshotDigest:v.optional(v.string()),snapshotManifest:v.optional(v.array(v.object({path:v.string(),blobSha:v.string(),bytes:v.number()}))),sourceBoundAt:v.optional(v.number()),resultProtocolVersion:v.optional(v.string()),resultDigest:v.optional(v.string()),deliveryStatus:v.optional(v.union(v.literal('not_requested'),v.literal('pending'),v.literal('delivered'),v.literal('failed'))),deliveryError:v.optional(v.string()),deliveryReceiptDigest:v.optional(v.string()),telegramMessageId:v.optional(v.number()),pdfMessageId:v.optional(v.number()),createdAt:v.number(),startedAt:v.optional(v.number()),completedAt:v.optional(v.number()),elapsedMs:v.optional(v.number()),dashboardSlug:v.string(),error:v.optional(v.string()),mappedFiles:v.number(),flowCount:v.number(),confirmedFindingCount:v.number(),rejectedFindingCount:v.number(),dependencyRiskCount:v.number(),analysisMode:v.union(v.literal('initial_full'),v.literal('incremental')),inputSchemaSnapshotId:v.optional(v.string()),outputSchemaSnapshotId:v.optional(v.string()),changedFileCount:v.number(),impactedFlowCount:v.number(),brief:v.optional(v.any()),capabilityProfile:v.optional(v.any()),paused:v.boolean(),cancelRequestedAt:v.optional(v.number())}).index('by_public_id',['publicId']).index('by_created_at',['createdAt']).index('by_repository',['repository']),
 agentSteps:defineTable({runId:v.id('runs'),analysisAttemptId:v.optional(v.string()),stepId:v.string(),parentStepId:v.optional(v.string()),role:v.string(),dynamicallySpawned:v.boolean(),objective:v.string(),status:v.string(),startedAt:v.number(),finishedAt:v.optional(v.number()),latencyMs:v.optional(v.number()),inputSummary:v.string(),outputSummary:v.optional(v.string()),tools:v.array(v.string()),revisions:v.array(v.string()),error:v.optional(v.string()),tokenUse:v.optional(v.number()),costUsd:v.optional(v.number())}).index('by_run',['runId']).index('by_parent',['runId','parentStepId']).index('by_status',['status']),
 graphNodes:defineTable({runId:v.id('runs'),nodeId:v.string(),kind:v.string(),name:v.string(),path:v.optional(v.string()),startLine:v.optional(v.number()),endLine:v.optional(v.number()),summary:v.string(),confidence:v.number()}).index('by_run',['runId']),
 graphEdges:defineTable({runId:v.id('runs'),edgeId:v.string(),from:v.string(),to:v.string(),kind:v.string(),evidence:v.array(evidence),confidence:v.number()}).index('by_run',['runId']),
 flows:defineTable({runId:v.id('runs'),flowId:v.string(),name:v.string(),data:v.any()}).index('by_run',['runId']),
 schemaSnapshots:defineTable({repositoryKey:v.string(),snapshotId:v.string(),version:v.number(),parentSnapshotId:v.optional(v.string()),sourceCommitSha:v.optional(v.string()),data:v.any(),createdAt:v.number(),confidenceSummary:v.string()}).index('by_repository_version',['repositoryKey','version']).index('by_snapshot_id',['snapshotId']),
 schemaDeltas:defineTable({runId:v.id('runs'),deltaId:v.string(),data:v.any(),createdAt:v.number()}).index('by_run',['runId']),
 principles:defineTable({runId:v.id('runs'),principleId:v.string(),statement:v.string(),scope:v.any(),provenance:v.array(v.string()),evidence:v.array(evidence),confidence:v.number(),status:v.string(),approvedExceptions:v.array(v.string()),lastValidatedAt:v.optional(v.number())}).index('by_run',['runId']),
 preferences:defineTable({repositoryKey:v.string(),preferenceId:v.string(),category:v.string(),value:v.string(),source:v.string(),evidence:v.array(evidence),confidence:v.number(),active:v.boolean()}).index('by_repository',['repositoryKey']),
 editorDiagnostics:defineTable({runId:v.id('runs'),repositoryKey:v.string(),findingId:v.string(),path:v.string(),startLine:v.number(),endLine:v.number(),severity:v.string(),title:v.string(),flowLabel:v.string(),principleStatement:v.string(),impact:v.string(),dashboardUrl:v.string(),githubPermalink:v.optional(v.string())}).index('by_run',['runId']).index('by_repository_path',['repositoryKey','path']),
 findings:defineTable({runId:v.id('runs'),findingId:v.string(),title:v.string(),category:v.string(),severity:v.string(),confidence:v.number(),status:v.string(),impact:v.string(),logicChain:v.array(v.string()),evidence:v.array(evidence),affectedNodeIds:v.array(v.string()),affectedFlowIds:v.array(v.string()),violatedInvariantIds:v.array(v.string()),businessImpact:v.string(),recommendation:v.string(),repairability:v.string(),rejectionReason:v.optional(v.string())}).index('by_run',['runId']).index('by_status',['status']),
 dependencies:defineTable({runId:v.id('runs'),packageName:v.string(),data:v.any()}).index('by_run',['runId']),

 repoMemories:defineTable({repositoryKey:v.string(),runId:v.id('runs'),snapshotId:v.string(),summary:v.string(),data:v.any(),createdAt:v.number()}).index('by_repository_created',['repositoryKey','createdAt']),
 roles:defineTable({name:v.string(),version:v.string(),enabled:v.boolean(),objective:v.string(),tools:v.array(v.string()),guardrails:v.array(v.string()),dynamic:v.boolean()}).index('by_name',['name']),
 evalCases:defineTable({caseId:v.string(),name:v.string(),version:v.string(),expected:v.any()}).index('by_case_id',['caseId']),
 evalRuns:defineTable({version:v.string(),startedAt:v.number(),completedAt:v.number(),passed:v.number(),failed:v.number(),data:v.any()}).index('by_version',['version']),
 managementActions:defineTable({runId:v.id('runs'),action:v.string(),actor:v.string(),createdAt:v.number(),details:v.optional(v.any())}).index('by_run',['runId']),
 waitlist:defineTable({email:v.string(),source:v.string(),joinedAt:v.number()}).index('by_email',['email']).index('by_joined_at',['joinedAt']),
 analysisAttempts:defineTable({runId:v.id('runs'),jobId:v.id('workerJobs'),attemptId:v.string(),ordinal:v.number(),status:v.union(v.literal('leased'),v.literal('source_bound'),v.literal('auditor_started'),v.literal('verifier_started'),v.literal('completed'),v.literal('failed'),v.literal('aborted'),v.literal('expired')),workerId:v.string(),leaseId:v.string(),leaseExpiresAt:v.number(),repositoryKey:v.optional(v.string()),sourceCommitSha:v.optional(v.string()),snapshotDigest:v.optional(v.string()),snapshotManifest:v.optional(v.array(v.object({path:v.string(),blobSha:v.string(),bytes:v.number()}))),coverageDigest:v.optional(v.string()),coverageDispositions:v.optional(v.array(v.object({path:v.string(),reason:v.union(v.literal('excluded_generated_or_vendored'),v.literal('unsupported_file_type'))}))),auditorCreationNonce:v.optional(v.string()),auditorCreationExpiresAt:v.optional(v.number()),auditorCreationConsumedAt:v.optional(v.number()),verifierCreationNonce:v.optional(v.string()),verifierCreationExpiresAt:v.optional(v.number()),verifierCreationConsumedAt:v.optional(v.number()),auditorSessionId:v.optional(v.string()),auditorRunId:v.optional(v.string()),auditorResultDigest:v.optional(v.string()),auditorReceiptDigest:v.optional(v.string()),verifierSessionId:v.optional(v.string()),verifierRunId:v.optional(v.string()),verifierResultDigest:v.optional(v.string()),verifierReceiptDigest:v.optional(v.string()),releaseSourceDigest:v.optional(v.string()),runtimeIdentityDigest:v.optional(v.string()),runtimeProcessPid:v.optional(v.number()),runtimeBootNonce:v.optional(v.string()),completionDigest:v.optional(v.string()),resultDigest:v.optional(v.string()),resultStatus:v.optional(v.string()),failureCode:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number(),completedAt:v.optional(v.number())}).index('by_attempt_id',['attemptId']).index('by_job_ordinal',['jobId','ordinal']).index('by_run_status',['runId','status']),
 deliveryOutbox:defineTable({runId:v.id('runs'),analysisAttemptId:v.string(),completionDigest:v.string(),target:v.optional(v.string()),status:v.union(v.literal('pending'),v.literal('leased'),v.literal('delivered'),v.literal('failed')),messageText:v.string(),messageDigest:v.string(),attachmentBase64:v.string(),attachmentName:v.string(),attachmentMediaType:v.string(),attachmentDigest:v.string(),messageStatus:v.union(v.literal('pending'),v.literal('sending'),v.literal('delivered'),v.literal('unknown')),messagePlatformReceiptId:v.optional(v.string()),messageReceiptDigest:v.optional(v.string()),attachmentStatus:v.union(v.literal('pending'),v.literal('sending'),v.literal('delivered'),v.literal('unknown')),attachmentPlatformReceiptId:v.optional(v.string()),attachmentReceiptDigest:v.optional(v.string()),deliveryAttemptCount:v.number(),availableAt:v.number(),leaseId:v.optional(v.string()),workerId:v.optional(v.string()),leasedAt:v.optional(v.number()),leaseExpiresAt:v.optional(v.number()),lastFailureCode:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number(),completedAt:v.optional(v.number())}).index('by_status_available',['status','availableAt']).index('by_lease_id',['leaseId']).index('by_run',['runId']),
 workerJobs:defineTable({runId:v.id('runs'),repoUrl:v.string(),requestedSourceCommitSha:v.optional(v.string()),status:v.union(v.literal('queued'),v.literal('leased'),v.literal('completed'),v.literal('failed'),v.literal('delivery_pending'),v.literal('delivery_leased')),attempts:v.number(),analysisAttemptCount:v.optional(v.number()),currentAttemptId:v.optional(v.string()),availableAt:v.number(),leaseId:v.optional(v.string()),workerId:v.optional(v.string()),leasedAt:v.optional(v.number()),leaseExpiresAt:v.optional(v.number()),createdAt:v.number(),updatedAt:v.number(),error:v.optional(v.string())}).index('by_status_available',['status','availableAt']).index('by_run',['runId']).index('by_lease_id',['leaseId']),
});
