import { z } from 'zod';

const evidence = z.object({ path:z.string().min(1), startLine:z.number().int().positive(), endLine:z.number().int().positive(), excerpt:z.string().min(1), explanation:z.string().min(1), githubPermalink:z.string().url().optional() }).strict().refine((value) => value.endLine >= value.startLine);
const node = z.object({ id:z.string().min(1), kind:z.enum(['entry_point','route','module','service','function','job','queue','data_store','domain_entity','external_api','configuration','environment_variable','dependency']), name:z.string(), path:z.string().optional(), startLine:z.number().optional(), endLine:z.number().optional(), summary:z.string(), confidence:z.number().min(0).max(1) }).strict();
const edge = z.object({ id:z.string().min(1), from:z.string(), to:z.string(), kind:z.enum(['calls','reads','writes','validates','transforms','authenticates','publishes','subscribes','retries','depends_on','transitions_to','configured_by','may_fail_at']), evidence:z.array(evidence), confidence:z.number().min(0).max(1) }).strict();
const invariant = z.object({ id:z.string(), statement:z.string(), scopeNodeIds:z.array(z.string()), evidence:z.array(evidence), confidence:z.number().min(0).max(1) }).strict();
const transition = z.object({ entity:z.string(), from:z.string(), to:z.string(), evidence:z.array(evidence), guarded:z.boolean() }).strict();
const flow = z.object({ id:z.string(), name:z.string(), trigger:z.string(), orderedNodeIds:z.array(z.string()), inputContract:z.array(z.string()), outputContract:z.array(z.string()), sideEffects:z.array(z.string()), stateTransitions:z.array(transition), invariants:z.array(invariant), failurePoints:z.array(z.string()), externalDependencies:z.array(z.string()), confidence:z.number().min(0).max(1) }).strict();
const principle = z.object({ id:z.string(), statement:z.string(), scopeNodeIds:z.array(z.string()), scopeFlowIds:z.array(z.string()), provenance:z.array(z.enum(['code','test','type_or_schema','configuration','documentation','repeated_convention','human_approval'])), evidence:z.array(evidence), confidence:z.number().min(0).max(1), status:z.enum(['derived','human_approved','contested','deprecated']), approvedExceptionIds:z.array(z.string()), lastValidatedAt:z.number().optional() }).strict();
const preference = z.object({ id:z.string(), category:z.enum(['library','naming','error_handling','validation','architecture','testing','formatting']), value:z.string(), source:z.enum(['repository_evidence','explicit_human_approval']), evidence:z.array(evidence), confidence:z.number(), active:z.boolean() }).strict();
const finding = z.object({ id:z.string(), title:z.string(), category:z.enum(['state_flow','integration','dependency','data_consistency','validation','async_failure','configuration','authentication','reliability']), severity:z.enum(['low','medium','high','critical']), confidence:z.number().min(0).max(1), status:z.enum(['confirmed','probable','needs_human_review','rejected']), impact:z.string(), logicChain:z.array(z.string()), evidence:z.array(evidence), affectedNodeIds:z.array(z.string()), affectedFlowIds:z.array(z.string()), violatedInvariantIds:z.array(z.string()), businessImpact:z.string(), recommendation:z.string(), repairability:z.literal('human_required'), rejectionReason:z.string().optional() }).strict();
const dependency = z.object({ packageName:z.string(), configuredRange:z.string(), resolvedVersion:z.string().optional(), latestStableVersion:z.string().optional(), currentReleaseDate:z.string().optional(), latestReleaseDate:z.string().optional(), deprecated:z.boolean(), classification:z.enum(['unverified','healthy','aging','majorly_behind','deprecated','abandoned_signal']), importingFiles:z.array(z.string()), affectedNodeIds:z.array(z.string()), affectedFlowIds:z.array(z.string()), probableUpgradeComplexity:z.enum(['unknown','low','medium','high']), safeAction:z.enum(['none','patch_update','minor_update','manual_migration','replace_package']), evidenceSummary:z.string() }).strict();

const diagnostic = z.object({ id:z.string(), runId:z.string(), findingId:z.string(), path:z.string(), startLine:z.number(), endLine:z.number(), severity:z.enum(['information','warning','error']), title:z.string(), flowLabel:z.string(), principleStatement:z.string(), impact:z.string(), dashboardUrl:z.string(), githubPermalink:z.string().optional() }).strict();
const manifest = z.object({ files:z.array(z.object({ path:z.string(), bytes:z.number(), language:z.string(), fingerprint:z.string().regex(/^[a-f0-9]{64}$/) }).strict()), languages:z.array(z.object({ language:z.string(), files:z.number(), percentage:z.number() }).strict()), ecosystems:z.array(z.string()), manifests:z.array(z.string()), validationCommands:z.array(z.string()), unsupportedRegions:z.array(z.string()), capability:z.object({ baseline:z.literal(true), deepSemantic:z.boolean() }).strict() }).strict();
const snapshot = z.object({ id:z.string(), repositoryKey:z.string(), version:z.number().int().positive(), parentSnapshotId:z.string().optional(), sourceCommitSha:z.string().regex(/^[a-f0-9]{40}$/i).optional(), createdAt:z.number(), nodeIds:z.array(z.string()), edgeIds:z.array(z.string()), flowIds:z.array(z.string()), principleIds:z.array(z.string()), preferenceIds:z.array(z.string()), dependencyRecordIds:z.array(z.string()), confidenceSummary:z.string(), fileFingerprints:z.record(z.string(),z.string().regex(/^[a-f0-9]{64}$/)), schemaDocument:z.string().optional() }).strict();

export const strictAnalysisResultSchema = z.object({ manifest, nodes:z.array(node), edges:z.array(edge), flows:z.array(flow), principles:z.array(principle), preferences:z.array(preference), findings:z.array(finding), dependencies:z.array(dependency), snapshot, editorDiagnostics:z.array(diagnostic) }).strict();
