import { findingSchema, type AnalysisResult, type CodebasePrinciple, type DependencyHealth, type EditorDiagnostic, type LogisticsEdge, type LogisticsNode, type RepositoryFile, type RepositoryManifest, type SourceEvidence, type SystemFlow, type WhiteboxFinding } from './contracts.js';
import { sanitizeRelativePath } from './security.js';
import { MAX_AUDIT_BYTES, MAX_AUDIT_FILES, MAX_AUDIT_FILE_BYTES } from './audit-limits.js';
import { sha256Text } from './canonical-integrity.js';

const LANGUAGE_BY_EXTENSION: Record<string, string> = {
  ts: 'TypeScript', tsx: 'TypeScript', js: 'JavaScript', jsx: 'JavaScript', py: 'Python', go: 'Go', rs: 'Rust', java: 'Java', kt: 'Kotlin', cs: 'C#', rb: 'Ruby', php: 'PHP', swift: 'Swift', c: 'C', h: 'C/C++', cpp: 'C++', cc: 'C++', json: 'JSON', yaml: 'YAML', yml: 'YAML', toml: 'TOML', md: 'Markdown'
};
const MANIFESTS: Record<string, string> = { 'package.json': 'npm', 'pyproject.toml': 'Python', 'requirements.txt': 'Python', 'go.mod': 'Go modules', 'Cargo.toml': 'Cargo', 'pom.xml': 'Maven', 'build.gradle': 'Gradle', 'composer.json': 'Composer', 'Gemfile': 'Bundler', 'Package.swift': 'SwiftPM', 'CMakeLists.txt': 'CMake' };
const EXCLUDED = /(^|\/)(node_modules|vendor|dist|build|coverage|\.git)(\/|$)|\.min\.(js|css)$/;


function stableHash(content:string){let first=0x811c9dc5,second=0x9e3779b9;for(let index=0;index<content.length;index+=1){const code=content.charCodeAt(index);first=Math.imul(first^code,0x01000193);second=Math.imul(second^code,0x85ebca6b);}return`${(first>>>0).toString(16).padStart(8,'0')}${(second>>>0).toString(16).padStart(8,'0')}`;}
function language(path: string) { const extension = path.split('.').pop()?.toLowerCase() ?? ''; return LANGUAGE_BY_EXTENSION[extension] ?? 'Text'; }
function numberedEvidence(file: RepositoryFile, lineIndex: number, explanation: string): SourceEvidence {
  const lines = file.content.split(/\r?\n/); const line = Math.max(0, Math.min(lineIndex, lines.length - 1));
  return { path: file.path, startLine: line + 1, endLine: line + 1, excerpt: (lines[line] ?? '').slice(0, 400), explanation };
}
function firstMatchingLine(file: RepositoryFile, pattern: RegExp) { return file.content.split(/\r?\n/).findIndex((line) => pattern.test(line)); }
function stableId(prefix: string, value: string) { return `${prefix}-${stableHash(value).slice(0, 12)}`; }

export async function buildManifest(inputFiles: RepositoryFile[]): Promise<RepositoryManifest> {
  const selected: RepositoryFile[] = []; let bytes = 0; const unsupportedRegions: string[] = [];
  for (const file of inputFiles) {
    sanitizeRelativePath(file.path);
    const size = new TextEncoder().encode(file.content).byteLength;
    if (EXCLUDED.test(file.path)) { unsupportedRegions.push(`${file.path}: generated or vendored`); continue; }
    if (size >= MAX_AUDIT_FILE_BYTES || selected.length >= MAX_AUDIT_FILES || bytes + size > MAX_AUDIT_BYTES) throw new Error(`Repository exceeds the complete analysis boundary at ${file.path}`);
    if (file.content.includes('\0')) { unsupportedRegions.push(`${file.path}: binary`); continue; }
    selected.push(file); bytes += size;
  }
  const manifestFiles = await Promise.all(selected.map(async(file) => ({ path: file.path, bytes: new TextEncoder().encode(file.content).byteLength, language: language(file.path), fingerprint: await sha256Text(file.content) })));
  const counts = new Map<string, number>(); for (const file of manifestFiles) counts.set(file.language, (counts.get(file.language) ?? 0) + 1);
  const languages = [...counts].map(([name, count]) => ({ language: name, files: count, percentage: Math.round(count / Math.max(1, manifestFiles.length) * 1000) / 10 })).sort((a, b) => b.files - a.files);
  const manifests = manifestFiles.map((file) => file.path).filter((path) => Object.keys(MANIFESTS).some((name) => path === name || path.endsWith(`/${name}`)));
  const ecosystems = [...new Set(manifests.map((path) => Object.entries(MANIFESTS).find(([name]) => path === name || path.endsWith(`/${name}`))?.[1]).filter((value): value is string => Boolean(value)))];
  const validationCommands: string[] = [];
  const packageFile = selected.find((file) => file.path === 'package.json' || file.path.endsWith('/package.json'));
  if (packageFile) { try { const parsed = JSON.parse(packageFile.content) as { scripts?: Record<string, string> }; if (parsed.scripts?.typecheck) validationCommands.push('npm run typecheck'); if (parsed.scripts?.lint) validationCommands.push('npm run lint'); if (parsed.scripts?.test) validationCommands.push('npm test'); } catch { unsupportedRegions.push(`${packageFile.path}: invalid JSON`); } }
  if (manifests.some((path) => path.endsWith('pyproject.toml') || path.endsWith('requirements.txt'))) validationCommands.push('python -m pytest');
  if (manifests.some((path) => path.endsWith('go.mod'))) validationCommands.push('go test ./...');
  if (manifests.some((path) => path.endsWith('Cargo.toml'))) validationCommands.push('cargo test');
  return { files: manifestFiles, languages, ecosystems, manifests, validationCommands, unsupportedRegions, capability: { baseline: true, deepSemantic: languages.some((item) => ['TypeScript','JavaScript','Python'].includes(item.language)) } };
}

function envOccurrences(files: RepositoryFile[]) {
  const patterns = [/process\.env\.([A-Z][A-Z0-9_]*)/g, /os\.environ\[['"]([A-Z][A-Z0-9_]*)['"]\]/g, /ENV\[['"]([A-Z][A-Z0-9_]*)['"]\]/g, /getenv\(['"]([A-Z][A-Z0-9_]*)['"]\)/g];
  const result: { name: string; file: RepositoryFile; line: number }[] = [];
  for (const file of files) for (const pattern of patterns) { pattern.lastIndex = 0; for (const match of file.content.matchAll(pattern)) { const before = file.content.slice(0, match.index); result.push({ name: match[1]!, file, line: before.split(/\r?\n/).length - 1 }); } }
  return result;
}
function envStem(name: string) { return name.replace(/PAYMENTS?/g, 'PAYMENT').replace(/SERVICES?/g, 'SERVICE'); }

export async function analyzeRepository(input: { repositoryKey: string; files: RepositoryFile[]; goal: string; runId?: string; dashboardUrl?: string; previousVersion?: number; analyzedAt?: number; sourceCommitSha?:string; coverageDigest?:string }): Promise<AnalysisResult> {
  const manifest=await buildManifest(input.files),allowed=new Set(manifest.files.map(file=>file.path)),files=input.files.filter(file=>allowed.has(file.path)),analyzedAt=input.analyzedAt??Date.now();
  const nodes:LogisticsNode[]=files.map(file=>({id:stableId('module',file.path),kind:file.path.match(/route|controller|handler/i)?'entry_point':'module',name:file.path,path:file.path,startLine:1,endLine:Math.max(1,file.content.split(/\r?\n/).length),summary:`${language(file.path)} source module`,confidence:1}));
  const edges:LogisticsEdge[]=[],flows:SystemFlow[]=[],findings:WhiteboxFinding[]=[];const envs=envOccurrences(files),externalId=stableId('external','external-http');
  for(const occurrence of envs){const envId=stableId('env',occurrence.name);if(!nodes.some(node=>node.id===envId))nodes.push({id:envId,kind:'environment_variable',name:occurrence.name,summary:'Runtime configuration input',confidence:1});const moduleId=stableId('module',occurrence.file.path);edges.push({id:stableId('edge',`${moduleId}:${envId}`),from:moduleId,to:envId,kind:'configured_by',evidence:[numberedEvidence(occurrence.file,occurrence.line,`Reads ${occurrence.name}`)],confidence:1});}
  const groups=new Map<string,typeof envs>();for(const env of envs){const stem=envStem(env.name);groups.set(stem,[...(groups.get(stem)??[]),env]);}
  for(const [stem,occurrences] of groups){const names=[...new Set(occurrences.map(item=>item.name))];if(names.length<2)continue;const evidence=occurrences.map(item=>numberedEvidence(item.file,item.line,`Uses ${item.name}`)),scope=[...new Set(occurrences.flatMap(item=>[stableId('module',item.file.path),stableId('env',item.name)]))],invariant={id:stableId('invariant',`config:${stem}`),statement:`The ${stem} integration must use one observed runtime configuration name.`,scopeNodeIds:scope,evidence,confidence:.97},flow:SystemFlow={id:stableId('flow',`config:${stem}`),name:`${stem} configuration resolution`,trigger:'Runtime configuration lookup',orderedNodeIds:scope,inputContract:names,outputContract:['One integration endpoint'],sideEffects:[],stateTransitions:[],invariants:[invariant],failurePoints:['Conflicting configuration names'],externalDependencies:[],confidence:.97};flows.push(flow);findings.push(findingSchema.parse({id:stableId('finding',`env:${stem}`),title:`Conflicting ${stem} configuration names`,category:'configuration',severity:'high',confidence:.97,status:'confirmed',impact:'The same integration can resolve different endpoints across components.',logicChain:names.map(name=>`Runtime configuration → ${name}`),evidence,affectedNodeIds:[...new Set(occurrences.map(item=>stableId('module',item.file.path)))],affectedFlowIds:[flow.id],violatedInvariantIds:[invariant.id],businessImpact:'Requests may fail or target an unintended service.',recommendation:`Normalize on the established ${names[0]} contract.`,repairability:'human_required'}));}
  const outboundPattern=/\bfetch\s*\(|\baxios\.(?:get|post|put|patch|delete|request)\s*\(|\brequests\.(?:get|post|put|patch|delete|request)\s*\(|\bhttps?\.(?:get|request)\s*\(/,runtimeFile=(path:string)=>!/(^|\/)(?:README(?:\.[^/]*)?|CHANGELOG(?:\.[^/]*)?|LICENSE(?:\.[^/]*)?|package\.json|composer\.json|Cargo\.toml|pyproject\.toml|[^/]*lock[^/]*)$|\.(?:md|mdx|lock)$/i.test(path),externalFiles=files.filter(file=>runtimeFile(file.path)&&outboundPattern.test(file.content));
  if(externalFiles.length)nodes.push({id:externalId,kind:'external_api',name:'External HTTP APIs',summary:'Outbound network side effects',confidence:.9});
  for(const file of externalFiles){const line=firstMatchingLine(file,outboundPattern),evidence=[numberedEvidence(file,line,'Observed outbound HTTP call')],moduleId=stableId('module',file.path),hasTimeout=/AbortSignal\.timeout|timeout\s*:|Timeout\(|timeout=/.test(file.content);edges.push({id:stableId('edge',`${file.path}:http`),from:moduleId,to:externalId,kind:'calls',evidence,confidence:.9});const invariant={id:stableId('invariant',`timeout:${file.path}`),statement:`The outbound call in ${file.path} must establish a bounded timeout failure path.`,scopeNodeIds:[moduleId,externalId],evidence,confidence:.9},flow:SystemFlow={id:stableId('flow',`http:${file.path}`),name:`${file.path} outbound HTTP call`,trigger:file.path,orderedNodeIds:[moduleId,externalId],inputContract:[],outputContract:['HTTP response or bounded failure'],sideEffects:['Outbound HTTP request'],stateTransitions:[],invariants:[invariant],failurePoints:['Remote service timeout'],externalDependencies:['External HTTP APIs'],confidence:.9};flows.push(flow);findings.push(findingSchema.parse({id:stableId('finding',`timeout:${file.path}`),title:hasTimeout?'Timeout concern disproved by surrounding code':'Outbound call lacks bounded timeout evidence',category:'reliability',severity:hasTimeout?'low':'medium',confidence:hasTimeout?.99:.88,status:hasTimeout?'rejected':'confirmed',impact:hasTimeout?'No active impact; the call is bounded.':'A stalled dependency can hold the observed HTTP flow open indefinitely.',logicChain:[file.path,'External HTTP APIs'],evidence,affectedNodeIds:[moduleId,externalId],affectedFlowIds:[flow.id],violatedInvariantIds:hasTimeout?[]:[invariant.id],businessImpact:hasTimeout?'None.':'Resource exhaustion and degraded availability.',recommendation:hasTimeout?'No repair.':'Add a bounded timeout using the repository error model.',repairability:'human_required',...(hasTimeout?{rejectionReason:'An explicit timeout failure boundary is present.'}:{})}));}
  for(const file of files){const assignments=[...file.content.matchAll(/(?:\w+\.)?status\s*=\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]/g)].map(match=>({state:match[1]!.toLowerCase(),line:file.content.slice(0,match.index).split(/\r?\n/).length-1}));if(!assignments.length)continue;let previous='unknown';const transitions:SystemFlow['stateTransitions']=[],regressions:{line:number;from:string;to:string}[]=[];for(const assignment of assignments){transitions.push({entity:file.path,from:previous,to:assignment.state,evidence:[numberedEvidence(file,assignment.line,`State changes from ${previous} to ${assignment.state}`)],guarded:/\bif\b/.test(file.content.split(/\r?\n/)[assignment.line]??'')});if(previous==='paid'&&assignment.state==='pending')regressions.push({line:assignment.line,from:previous,to:assignment.state});previous=assignment.state;}const moduleId=stableId('module',file.path),invariant={id:stableId('invariant',`state:${file.path}`),statement:`Observed state transitions in ${file.path} must not regress paid to pending.`,scopeNodeIds:[moduleId],evidence:transitions.flatMap(item=>item.evidence),confidence:.95},flow:SystemFlow={id:stableId('flow',`state:${file.path}`),name:`${file.path} state transitions`,trigger:file.path,orderedNodeIds:[moduleId],inputContract:['Current state'],outputContract:['Next state'],sideEffects:[],stateTransitions:transitions,invariants:[invariant],failurePoints:['Invalid state regression'],externalDependencies:[],confidence:.95};flows.push(flow);for(const regression of regressions)findings.push(findingSchema.parse({id:stableId('finding',`state:${file.path}:${regression.line}`),title:'Paid state regresses to pending',category:'state_flow',severity:'critical',confidence:.98,status:'confirmed',impact:'A completed payment can re-enter a pre-payment state.',logicChain:[regression.from,regression.to],evidence:[numberedEvidence(file,regression.line,'The observed assignment moves a paid entity back to pending')],affectedNodeIds:[moduleId],affectedFlowIds:[flow.id],violatedInvariantIds:[invariant.id],businessImpact:'Orders may be retried or fulfilled inconsistently after payment.',recommendation:'Guard the transition using the repository state model.',repairability:'human_required'}));}
  const principles:CodebasePrinciple[]=flows.flatMap(flow=>flow.invariants.map(invariant=>({id:invariant.id,statement:invariant.statement,scopeNodeIds:invariant.scopeNodeIds,scopeFlowIds:[flow.id],provenance:['code'],evidence:invariant.evidence,confidence:invariant.confidence,status:'derived',approvedExceptionIds:[],lastValidatedAt:analyzedAt})));
  const dependencies:DependencyHealth[]=[];for(const file of files.filter(candidate=>candidate.path.endsWith('package.json'))){try{const parsed=JSON.parse(file.content) as{dependencies?:Record<string,string>};for(const[packageName,configuredRange]of Object.entries(parsed.dependencies??{}))dependencies.push({packageName,configuredRange,deprecated:false,classification:'unverified',importingFiles:[file.path],affectedNodeIds:[stableId('module',file.path)],affectedFlowIds:[],probableUpgradeComplexity:'unknown',safeAction:'none',evidenceSummary:`Declared in ${file.path}; no registry or advisory health claim was performed.`});}catch{/* manifest limitation */}}
  const runId=input.runId??'analysis',dashboardUrl=input.dashboardUrl??`/runs/${runId}`,editorDiagnostics:EditorDiagnostic[]=findings.filter(finding=>finding.status!=='rejected'&&finding.confidence>=.8&&['medium','high','critical'].includes(finding.severity)).map(finding=>{const evidence=finding.evidence[0]!,flow=flows.find(item=>finding.affectedFlowIds.includes(item.id))!,principle=principles.find(item=>finding.violatedInvariantIds.includes(item.id))!;return{id:stableId('diagnostic',finding.id),runId,findingId:finding.id,path:evidence.path,startLine:evidence.startLine,endLine:evidence.endLine,severity:finding.severity==='high'||finding.severity==='critical'?'error':'warning',title:finding.title,flowLabel:flow.name,principleStatement:principle.statement,impact:finding.impact,dashboardUrl,...(evidence.githubPermalink?{githubPermalink:evidence.githubPermalink}:{})}});
  const fileFingerprints=Object.fromEntries(manifest.files.map(file=>[file.path,file.fingerprint])),snapshotId=`schema-${(await sha256Text(`${input.repositoryKey}:${input.sourceCommitSha??'unbound'}:${input.previousVersion??0}:${JSON.stringify(fileFingerprints)}`)).slice(0,12)}`,dependencyRecordIds=await Promise.all(dependencies.map(async dependency=>`dependency-${(await sha256Text(dependency.packageName)).slice(0,12)}`));
  const snapshot={id:snapshotId,repositoryKey:input.repositoryKey,version:(input.previousVersion??0)+1,...(input.sourceCommitSha?{sourceCommitSha:input.sourceCommitSha}:{}),createdAt:analyzedAt,nodeIds:nodes.map(node=>node.id),edgeIds:edges.map(edge=>edge.id),flowIds:flows.map(flow=>flow.id),principleIds:principles.map(principle=>principle.id),preferenceIds:[],dependencyRecordIds,confidenceSummary:`${manifest.capability.deepSemantic?'Deep-semantic signals available':'Baseline analysis'}; ${findings.filter(finding=>finding.status==='confirmed').length} confirmed findings.`,fileFingerprints};
  return{manifest,nodes,edges,flows,principles,preferences:[],findings,dependencies,snapshot,editorDiagnostics};
}
