const absolutePath=/(?:^|[\s"'`(])(?:\/Users\/[^\s"'`)]+|\/home\/[^\s"'`)]+|[A-Za-z]:\\[^\s"'`)]+)/g;
function text(value:unknown){return typeof value==='string'?[...value.replace(absolutePath,' [redacted-path]')].filter(character=>{const code=character.charCodeAt(0);return code>=32&&code!==127||code===9||code===10||code===13;}).join(''):value;}
function list(value:unknown){return Array.isArray(value)?value.map(text):[];}
function path(value:unknown){if(typeof value!=='string'||!value||value.startsWith('/')||value.includes('..')||value.includes('\\')||value.includes('\0'))return'[redacted-path]';return value;}
function permalink(value:unknown){if(typeof value!=='string')return undefined;try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='github.com'?value:undefined;}catch{return undefined;}}
function evidence(value: Record<string, unknown>) {const link=permalink(value.githubPermalink);return { path:path(value.path), startLine:value.startLine, endLine:value.endLine, excerpt:text(value.excerpt), explanation:text(value.explanation), ...(link?{githubPermalink:link}:{}) };}
function evidenceList(value: unknown) { return Array.isArray(value) ? value.map((item) => evidence(item as Record<string,unknown>)) : []; }

export function projectPublicRun(run: Record<string,unknown>) {
  const keys = ['publicId','repository','mode','status','currentStage','createdAt','startedAt','completedAt','elapsedMs','sourceCommitSha','mappedFiles','flowCount','confirmedFindingCount','rejectedFindingCount','dependencyRiskCount','analysisMode','changedFileCount','impactedFlowCount','deliveryStatus'] as const;
  const result: Record<string,unknown> = {};
  for (const key of keys) if (run[key] !== undefined) result[key] = typeof run[key]==='string'?text(run[key]):run[key];
  result.sourceBound = typeof run.sourceCommitSha === 'string' && typeof run.snapshotDigest === 'string';
  result.resultBound = typeof run.resultDigest === 'string' && run.resultProtocolVersion === 'whitebox-verified-result-v1';
  result.schemaPublished = typeof run.outputSchemaSnapshotId === 'string';
  return result;
}
export const sanitizePublicRun = projectPublicRun;
export function projectPublicStep(step: Record<string,unknown>) {return { role:text(step.role), status:text(step.status), objective:text(step.objective), startedAt:step.startedAt, ...(step.finishedAt === undefined ? {} : { finishedAt:step.finishedAt }), ...(step.latencyMs === undefined ? {} : { latencyMs:step.latencyMs }), dynamicallySpawned:step.dynamicallySpawned };}
export const sanitizePublicStep = projectPublicStep;
export function projectPublicNode(node: Record<string,unknown>) {return { nodeId:node.nodeId, kind:text(node.kind), name:text(node.name), ...(node.path === undefined ? {} : { path:path(node.path) }), ...(node.startLine === undefined ? {} : { startLine:node.startLine }), ...(node.endLine === undefined ? {} : { endLine:node.endLine }), summary:text(node.summary), confidence:node.confidence };}
export function projectPublicEdge(edge: Record<string,unknown>) {return { edgeId:edge.edgeId, from:edge.from, to:edge.to, kind:text(edge.kind), evidence:evidenceList(edge.evidence), confidence:edge.confidence };}
export function projectPublicFlow(row: Record<string,unknown>) {const data = (row.data ?? {}) as Record<string,unknown>;const transitions = Array.isArray(data.stateTransitions) ? data.stateTransitions.map((item) => { const value=item as Record<string,unknown>; return { entity:text(value.entity), from:text(value.from), to:text(value.to), evidence:evidenceList(value.evidence), guarded:value.guarded }; }) : [];const invariants = Array.isArray(data.invariants) ? data.invariants.map((item) => { const value=item as Record<string,unknown>; return { id:value.id, statement:text(value.statement), scopeNodeIds:Array.isArray(value.scopeNodeIds)?value.scopeNodeIds:[], evidence:evidenceList(value.evidence), confidence:value.confidence }; }) : [];return { flowId:row.flowId, name:text(row.name), data:{ id:data.id, name:text(data.name), trigger:text(data.trigger), orderedNodeIds:Array.isArray(data.orderedNodeIds)?data.orderedNodeIds:[], inputContract:list(data.inputContract), outputContract:list(data.outputContract), sideEffects:list(data.sideEffects), stateTransitions:transitions, invariants, failurePoints:list(data.failurePoints), externalDependencies:list(data.externalDependencies), confidence:data.confidence } };}
export function projectPublicFinding(row: Record<string,unknown>) {return { findingId:row.findingId, title:text(row.title), category:text(row.category), severity:row.severity, confidence:row.confidence, status:row.status, impact:text(row.impact), logicChain:list(row.logicChain), evidence:evidenceList(row.evidence), affectedNodeIds:Array.isArray(row.affectedNodeIds)?row.affectedNodeIds:[], affectedFlowIds:Array.isArray(row.affectedFlowIds)?row.affectedFlowIds:[], violatedInvariantIds:Array.isArray(row.violatedInvariantIds)?row.violatedInvariantIds:[], businessImpact:text(row.businessImpact), recommendation:text(row.recommendation), repairability:'human_required' };}
export function projectPublicDependency(row: Record<string,unknown>) {const data=(row.data ?? {}) as Record<string,unknown>;return { packageName:text(row.packageName), data:{ configuredRange:text(data.configuredRange), classification:'unverified', verificationStatus:'Registry and advisory health were not queried', safeAction:'none' } };}
export function projectPublicDiagnostic(row: Record<string,unknown>) {const link=permalink(row.githubPermalink);return { findingId:row.findingId, path:path(row.path), startLine:row.startLine, endLine:row.endLine, severity:row.severity, title:text(row.title), flowLabel:text(row.flowLabel), principleStatement:text(row.principleStatement), impact:text(row.impact), ...(link?{githubPermalink:link}:{}) };}
export function projectPublicDelta(row: Record<string,unknown>) {const data=(row.data ?? {}) as Record<string,unknown>;return { deltaId:row.deltaId, createdAt:row.createdAt, data:{ conciseSummary:text(data.conciseSummary) } };}
export function projectPublicSnapshot(row: Record<string,unknown>, schemaDocument: string) {return { snapshotId:row.snapshotId, version:row.version, ...(row.sourceCommitSha === undefined ? {} : { sourceCommitSha:row.sourceCommitSha }), createdAt:row.createdAt, confidenceSummary:text(row.confidenceSummary), data:{ schemaDocument:text(schemaDocument) } };}
