import { z } from 'zod';
import { parseGitHubRepository } from '../../../packages/core/src/security.js';
import type { RepositoryFile } from '../../../packages/core/src/contracts.js';
const treeSchema=z.object({sha:z.string(),tree:z.array(z.object({path:z.string(),type:z.string(),size:z.number().optional(),url:z.string().optional()})),truncated:z.boolean().optional()});
const sourceExtensions=/\.(?:ts|tsx|js|jsx|py|go|rs|java|kt|cs|rb|php|swift|c|cc|cpp|h|hpp|json|ya?ml|toml|md)$/i;
const excluded=/(^|\/)(node_modules|vendor|dist|build|coverage|\.git)(\/|$)|\.min\./;
export class GitHubClient {
  constructor(private readonly token?:string,private readonly fetcher:typeof fetch=fetch){}
  private headers(){return {Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(this.token?{Authorization:`Bearer ${this.token}`}:{})};}
  private async request(url:string,init:RequestInit={}){const response=await this.fetcher(url,{...init,headers:{...this.headers(),...init.headers}});if(!response.ok)throw new Error(`GitHub request failed (${response.status})`);return response;}
  async inspect(url:string){const repo=parseGitHubRepository(url);const meta=await (await this.request(`https://api.github.com/repos/${repo.key}`)).json() as {default_branch:string;size:number;private:boolean};if(meta.private)throw new Error('Private repositories are not supported');if(meta.size>100000)throw new Error('Repository exceeds the 100 MB safety limit');const branch=meta.default_branch;const tree=treeSchema.parse(await (await this.request(`https://api.github.com/repos/${repo.key}/git/trees/${encodeURIComponent(branch)}?recursive=1`)).json());if(tree.truncated)throw new Error('GitHub tree was truncated; repository is too large for bounded analysis');const candidates=tree.tree.filter((item)=>item.type==='blob'&&item.path&&sourceExtensions.test(item.path)&&!excluded.test(item.path)&&(item.size??0)<200000).slice(0,60);let bytes=0;const files:RepositoryFile[]=[];for(const item of candidates){if(bytes+(item.size??0)>750000)break;const response=await this.request(`https://raw.githubusercontent.com/${repo.key}/${encodeURIComponent(branch)}/${item.path.split('/').map(encodeURIComponent).join('/')}`);const content=await response.text();if(content.includes('\0'))continue;files.push({path:item.path,content});bytes+=Buffer.byteLength(content);}return {...repo,defaultBranch:branch,sourceSha:tree.sha,files};}
  async openPullRequest(input:{repositoryKey:string;head:string;base:string;title:string;body:string}){if(!this.token)throw new Error('GITHUB_TOKEN is required to publish');const response=await this.request(`https://api.github.com/repos/${input.repositoryKey}/pulls`,{method:'POST',body:JSON.stringify({title:input.title,head:input.head,base:input.base,body:input.body})});const data=z.object({html_url:z.string().url(),number:z.number()}).parse(await response.json());return {url:data.html_url,number:data.number};}
}
