import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {analyzeRepository} from '../packages/core/src/analyzer.js';
import {assertCanonicalAnalysis} from '../packages/core/src/canonical-integrity.js';
import {canonicalSchemaDocument} from '../packages/core/src/canonical-artifacts.js';
import {classifyCompleteAuditTree} from '../packages/core/src/github-audit-tree.js';
import {assertProducerAuthorityConsumable} from '../convex/lib/producer_authority.js';
import {hermesAuditorRunInput,hermesVerifierRunInput,WHITEBOX_AUDITOR_PROMPT_DIGEST,WHITEBOX_VERIFIER_PROMPT_DIGEST} from '../packages/core/src/hermes-authority.js';
import {HermesRunCreationError,HermesRunsClient} from '../packages/core/src/hermes-client.js';
import {detectorFindingClaimDigest,mergeHermesVerifiedResult,reconcileHermesReview} from '../packages/core/src/hermes-result.js';
import {parseTelegramDeliveryReceipt} from '../packages/core/src/telegram-delivery.js';
import {completionReplay,deliveryLegTransition,expiredDeliveryDisposition} from '../convex/lib/attempt_lifecycle.js';
import {assertSnapshotOwnership} from '../convex/lib/completion_binding.js';
import {canonicalDeliveryClaim} from '../convex/lib/delivery_lifecycle.js';
import {projectPublicFinding,projectPublicNode,projectPublicRun} from '../convex/lib/public_run.js';

const commit='0123456789abcdef0123456789abcdef01234567',nextCommit='1123456789abcdef0123456789abcdef01234567',privateGoalCanary='PRIVATE_GOAL_CANARY',producerCanary='PRODUCER_CANARY telegram:-100999 /Users/private/secret.ts';
const files=[{path:'src/config.ts',content:'export const endpoint = process.env.SERVICE_URL;'},{path:'src/other.ts',content:'export const endpoint = process.env.SERVICES_URL;'},{path:'src/client.ts',content:'export async function load(url:string){ return fetch(url); }'}];
const analysis=await analyzeRepository({repositoryKey:'acme/demo',files,goal:privateGoalCanary,analyzedAt:1,sourceCommitSha:commit,coverageDigest:'a'.repeat(64)});assertCanonicalAnalysis(analysis,files);const detector=analysis.findings.find(finding=>finding.category==='configuration')!;
const proposal={version:'whitebox-auditor-proposal-v1' as const,repository:'acme/demo',sourceCommitSha:commit,summary:producerCanary,candidates:[{candidateId:detector.id,detectorFindingId:detector.id,detectorClaimDigest:await detectorFindingClaimDigest(detector),repairability:'human_required' as const}]};
const verification={version:'whitebox-verified-result-v1' as const,repository:'acme/demo',sourceCommitSha:commit,summary:producerCanary,findings:[{candidateId:detector.id,status:'confirmed' as const,confidence:.95}]};
const omitted=reconcileHermesReview(proposal,{...verification,findings:[]}).errors.some(error=>error.includes('omitted')),invented=reconcileHermesReview(proposal,{...verification,findings:[...verification.findings,{candidateId:'candidate-invented-self-approved',status:'confirmed' as const,confidence:1}]}).errors.some(error=>error.includes('unproposed')),reconciled=reconcileHermesReview(proposal,verification),merged=await mergeHermesVerifiedResult(analysis,files,reconciled.result!),confirmed=merged.analysis.findings.find(finding=>finding.status==='confirmed'&&finding.category==='configuration');
let repairAuthorityRejected=false;try{assertCanonicalAnalysis({...analysis,repairs:[{id:'forged'}] as never},files);}catch{repairAuthorityRejected=true;}
const unrecognizedProposal={...proposal,candidates:[{...proposal.candidates[0]!,candidateId:'candidate-unrecognized-auth',detectorFindingId:'candidate-unrecognized-auth'}]},unrecognizedVerification={...verification,findings:[{candidateId:'candidate-unrecognized-auth',status:'confirmed' as const,confidence:1}]},unrecognizedReconciled=reconcileHermesReview(unrecognizedProposal,unrecognizedVerification),unrecognized=await mergeHermesVerifiedResult(analysis,files,unrecognizedReconciled.result!);
const publicRun=projectPublicRun({publicId:'WB-TEST',repository:'acme/demo',goal:privateGoalCanary,telegramUserId:privateGoalCanary,snapshotDigest:'a'.repeat(64),sourceCommitSha:commit,resultDigest:'b'.repeat(64),resultProtocolVersion:'whitebox-verified-result-v1'}),publicNode=projectPublicNode({nodeId:'n',kind:'module',name:'/Users/private/secret.ts',path:'/Users/private/secret.ts',summary:'from /Users/private/secret.ts',confidence:1}),publicFinding=confirmed?projectPublicFinding({findingId:confirmed.id,...confirmed}):{};
const coverage=classifyCompleteAuditTree([{path:'src/config.ts',type:'blob',size:10,sha:'a'.repeat(40)},{path:'logo.png',type:'blob',size:10,sha:'b'.repeat(40)}]);let gitlinkRejected=false;try{classifyCompleteAuditTree([{path:'src/config.ts',type:'blob',size:10},{path:'linked',type:'commit',sha:'a'.repeat(40)}]);}catch{gitlinkRejected=true;}
const serverClaim=canonicalDeliveryClaim({target:'telegram:-1001:7',messageText:'canonical',messageDigest:'a'.repeat(64),attachmentBase64:'cGRm',attachmentName:'report.pdf',attachmentMediaType:'application/pdf',attachmentDigest:'b'.repeat(64),messageStatus:'pending',attachmentStatus:'pending'},'message');
let ambiguousSuppressed=false;try{await new HermesRunsClient({baseUrl:'http://127.0.0.1:1',environment:'test',fetcher:async()=>{throw new Error('lost response');}}).createRun({input:'x',sessionId:'s',instructions:'i',creationAuthority:{authority:{version:'whitebox-producer-authority-v1'},signature:'a'.repeat(64)}});}catch(error){ambiguousSuppressed=error instanceof HermesRunCreationError&&error.retryable===false;}
const nextAnalysis=await analyzeRepository({repositoryKey:'acme/demo',files,goal:'audit_only',analyzedAt:1,sourceCommitSha:nextCommit,coverageDigest:'a'.repeat(64)}),auditorInput=await hermesAuditorRunInput('WB-TEST','acme/demo',commit,'b'.repeat(64),'a'.repeat(64),files,analysis.findings),verifierInput=await hermesVerifierRunInput('WB-TEST','acme/demo',commit,'b'.repeat(64),'a'.repeat(64),files,proposal,analysis.findings),schema=canonicalSchemaDocument({publicId:'WB-TEST',repository:'acme/demo',mode:'audit_only'},merged.analysis),sha=(value:string)=>createHash('sha256').update(value).digest('hex'),[auditorPrompt,verifierPrompt]=await Promise.all([readFile('hermes/WHITEBOX_AUDITOR_SYSTEM_PROMPT.md','utf8'),readFile('hermes/WHITEBOX_POC_SYSTEM_PROMPT.md','utf8')]);
let conflictingReplayRejected=false,snapshotReuseRejected=false,destinationMismatchRejected=false,unexpectedTopicRejected=false,deliveryConflictRejected=false,producerAuthorityReplayRejected=false;try{completionReplay('a','b');}catch{conflictingReplayRejected=true;}try{assertSnapshotOwnership({repositoryKey:'acme/demo',sourceCommitSha:commit},'acme/demo',nextCommit);}catch{snapshotReuseRejected=true;}try{await parseTelegramDeliveryReceipt(JSON.stringify({success:true,platform:'telegram',chat_id:'-1002',message_id:'7'}),'telegram:-1001');}catch{destinationMismatchRejected=true;}try{await parseTelegramDeliveryReceipt(JSON.stringify({success:true,platform:'telegram',chat_id:'-1001',message_thread_id:7,message_id:'7'}),'telegram:-1001');}catch{unexpectedTopicRejected=true;}
try{assertProducerAuthorityConsumable({nonce:'a'.repeat(32),issuedAt:1,expiresAt:2},{nonce:'a'.repeat(32),expiresAt:2,consumedAt:1},1);}catch{producerAuthorityReplayRejected=true;}try{deliveryLegTransition('delivered','delivered','7','8');}catch{deliveryConflictRejected=true;}
const checks={repairAuthorityRejected,gitlinkRejected,unexpectedTopicRejected,producerAuthorityReplayRejected,candidateOmissionRejected:omitted,inventedCandidateRejected:invented,trustedSemanticAuthority:Boolean(confirmed?.affectedFlowIds.length&&confirmed.violatedInvariantIds.length&&confirmed.title!==producerCanary),unrecognizedProducerCandidateRejected:unrecognized.errors.some(error=>error.includes('Unknown detector')),producerProseNotPublic:!JSON.stringify(publicFinding).includes(producerCanary),privateGoalOmitted:!JSON.stringify(publicRun).includes(privateGoalCanary)&&!auditorInput.includes(privateGoalCanary)&&!verifierInput.includes(privateGoalCanary),localPathRedacted:!JSON.stringify(publicNode).includes('/Users/'),unsupportedBlobDisposition:coverage.dispositions.some(item=>item.path==='logo.png'&&item.reason==='unsupported_file_type'),ambiguousProducerRetrySuppressed:ambiguousSuppressed,approvedPromptDigestsBound:sha(auditorPrompt)===WHITEBOX_AUDITOR_PROMPT_DIGEST&&sha(verifierPrompt)===WHITEBOX_VERIFIER_PROMPT_DIGEST,sourceCommitChangesSnapshotIdentity:analysis.snapshot.id!==nextAnalysis.snapshot.id,firstCompletionReachable:completionReplay(undefined,'a')==='first',exactCompletionReplayIdempotent:completionReplay('a','a')==='replay',conflictingCompletionRejected:conflictingReplayRejected,terminalSnapshotReuseRejected:snapshotReuseRejected,ambiguousSendSuppressed:expiredDeliveryDisposition('sending','pending').terminal,serverAuthoritativeDeliveryClaim:serverClaim.target==='telegram:-1001:7'&&serverClaim.messageText==='canonical'&&!('outboxId'in serverClaim),destinationMismatchRejected,deliveryReceiptConflictRejected:deliveryConflictRejected,dependencyClaimsRemainUnverified:analysis.dependencies.every(item=>item.classification==='unverified'),canonicalSchemaOmitsPrivateAndProducerProse:!schema.includes(privateGoalCanary)&&!schema.includes(producerCanary)};
console.log(JSON.stringify({checks},null,2));if(!Object.values(checks).every(Boolean))process.exit(1);
